; NSIS installer for VpnCloud. Built by contrib/windows/package.sh
;   makensis -DVERSION=x.y.z -DSTAGE=/path -DOUTFILE=/path/setup.exe this.nsi
;
; Payload: vpncloud.exe, vpncloud-gui.exe, wintun.dll (TUN), licenses, example
; config. TAP (tap-windows6) is a signed kernel driver and is *not* bundled.

!ifndef VERSION
  !error "Define VERSION (e.g. -DVERSION=2.4.3)"
!endif
!ifndef STAGE
  !error "Define STAGE (directory containing vpncloud.exe, wintun.dll, ...)"
!endif
!ifndef OUTFILE
  !error "Define OUTFILE"
!endif

Unicode true
ManifestDPIAware true
SetCompressor /SOLID lzma
RequestExecutionLevel admin
SetOverwrite on

Name "VpnCloud ${VERSION}"
OutFile "${OUTFILE}"
InstallDir "$PROGRAMFILES64\VpnCloud"
InstallDirRegKey HKLM "Software\VpnCloud" "InstallDir"
BrandingText "VpnCloud ${VERSION}"

VIProductVersion "${VERSION}.0"
VIAddVersionKey "ProductName" "VpnCloud"
VIAddVersionKey "ProductVersion" "${VERSION}"
VIAddVersionKey "FileDescription" "VpnCloud installer"
VIAddVersionKey "FileVersion" "${VERSION}.0"
VIAddVersionKey "LegalCopyright" "GPL-3.0. Wintun prebuilt DLL: WireGuard LLC"

!include "MUI2.nsh"
!include "x64.nsh"
!include "LogicLib.nsh"
!include "WinMessages.nsh"
!include "WordFunc.nsh"
!include "StrFunc.nsh"
${StrStr}
!insertmacro WordReplace
!insertmacro un.WordReplace

!define MUI_ABORTWARNING
!define MUI_FINISHPAGE_RUN "$INSTDIR\vpncloud-gui.exe"
!define MUI_FINISHPAGE_RUN_TEXT "Launch VpnCloud GUI"
!define MUI_FINISHPAGE_RUN_NOTCHECKED
!define MUI_FINISHPAGE_NOAUTOCLOSE

!insertmacro MUI_PAGE_LICENSE "${STAGE}/LICENSE.md"
!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

Function .onInit
  SetRegView 64
  ${If} ${RunningX64}
    StrCpy $INSTDIR "$PROGRAMFILES64\VpnCloud"
  ${EndIf}
FunctionEnd

Section "VpnCloud (required)" SecCore
  SectionIn RO
  SetOutPath $INSTDIR
  File "${STAGE}/vpncloud.exe"
  File "${STAGE}/wintun.dll"
  File "${STAGE}/LICENSE.md"
  File "${STAGE}/WINTUN-LICENSE.txt"
  File "${STAGE}/README.txt"
  File "${STAGE}/example.net.disabled"

  CreateDirectory "$SMPROGRAMS\VpnCloud"
  CreateShortCut "$SMPROGRAMS\VpnCloud\Uninstall VpnCloud.lnk" "$INSTDIR\Uninstall.exe"

  WriteRegStr HKLM "Software\VpnCloud" "InstallDir" "$INSTDIR"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\VpnCloud" "DisplayName" "VpnCloud ${VERSION}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\VpnCloud" "DisplayVersion" "${VERSION}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\VpnCloud" "Publisher" "Lyamc"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\VpnCloud" "URLInfoAbout" "https://github.com/Lyamc/vpncloud"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\VpnCloud" "UninstallString" "$INSTDIR\Uninstall.exe"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\VpnCloud" "QuietUninstallString" '"$INSTDIR\Uninstall.exe" /S'
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\VpnCloud" "InstallLocation" "$INSTDIR"
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\VpnCloud" "NoModify" 1
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\VpnCloud" "NoRepair" 1
  WriteUninstaller "$INSTDIR\Uninstall.exe"
SectionEnd

Section "Desktop GUI" SecGui
  SetOutPath $INSTDIR
  File "${STAGE}/vpncloud-gui.exe"
  CreateShortCut "$SMPROGRAMS\VpnCloud\VpnCloud.lnk" "$INSTDIR\vpncloud-gui.exe"
SectionEnd

Section "Add VpnCloud to PATH" SecPath
  Push $INSTDIR
  Call AddToPath
SectionEnd

Section /o "Windows service (LocalSystem, auto-start)" SecService
  ; Registers the service but does not start it: edit
  ; %ProgramData%\VpnCloud\vpncloud.yaml first (password / peers / --ip).
  ReadEnvStr $R9 ProgramData
  ${If} $R9 == ""
    StrCpy $R9 "$WINDIR\..\ProgramData"
  ${EndIf}
  CreateDirectory "$R9\VpnCloud"
  ${If} ${FileExists} "$R9\VpnCloud\vpncloud.yaml"
  ${Else}
    FileOpen $0 "$R9\VpnCloud\vpncloud.yaml" w
    FileWrite $0 "# Generated by VpnCloud setup$\r$\n"
    FileWrite $0 "listen: 3210$\r$\n"
    FileWrite $0 "tray: false$\r$\n"
    FileClose $0
  ${EndIf}
  nsExec::ExecToLog '"$INSTDIR\vpncloud.exe" service install --config "$R9\VpnCloud\vpncloud.yaml"'
SectionEnd

LangString DESC_SecCore ${LANG_ENGLISH} "CLI, Wintun TUN driver DLL, licenses, and an example config. Required."
LangString DESC_SecGui ${LANG_ENGLISH} "Iced desktop GUI (vpncloud-gui.exe) and a Start Menu shortcut."
LangString DESC_SecPath ${LANG_ENGLISH} "Prepend the install folder to the machine PATH so vpncloud is on the command line."
LangString DESC_SecService ${LANG_ENGLISH} "Register a LocalSystem auto-start service. Does not start the VPN until you edit C:\ProgramData\VpnCloud\vpncloud.yaml."

!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SecCore} $(DESC_SecCore)
  !insertmacro MUI_DESCRIPTION_TEXT ${SecGui} $(DESC_SecGui)
  !insertmacro MUI_DESCRIPTION_TEXT ${SecPath} $(DESC_SecPath)
  !insertmacro MUI_DESCRIPTION_TEXT ${SecService} $(DESC_SecService)
!insertmacro MUI_FUNCTION_DESCRIPTION_END

Function AddToPath
  Exch $0
  Push $1
  Push $2
  ReadRegStr $1 HKLM "SYSTEM\CurrentControlSet\Control\Session Manager\Environment" "Path"
  ${StrStr} $2 $1 $0
  ${If} $2 == ""
    ${If} $1 == ""
      StrCpy $1 $0
    ${Else}
      StrCpy $1 "$1;$0"
    ${EndIf}
    WriteRegExpandStr HKLM "SYSTEM\CurrentControlSet\Control\Session Manager\Environment" "Path" $1
    SendMessage ${HWND_BROADCAST} ${WM_WININICHANGE} 0 "STR:Environment" /TIMEOUT=5000
  ${EndIf}
  Pop $2
  Pop $1
  Pop $0
FunctionEnd

Function un.RemoveFromPath
  Exch $0
  Push $1
  ReadRegStr $1 HKLM "SYSTEM\CurrentControlSet\Control\Session Manager\Environment" "Path"
  ${un.WordReplace} "$1" ";$0" "" "+" $1
  ${un.WordReplace} "$1" "$0;" "" "+" $1
  ${un.WordReplace} "$1" "$0" "" "+" $1
  WriteRegExpandStr HKLM "SYSTEM\CurrentControlSet\Control\Session Manager\Environment" "Path" $1
  SendMessage ${HWND_BROADCAST} ${WM_WININICHANGE} 0 "STR:Environment" /TIMEOUT=5000
  Pop $1
  Pop $0
FunctionEnd

Section "Uninstall"
  SetRegView 64
  nsExec::ExecToLog '"$INSTDIR\vpncloud.exe" service uninstall'
  Push $INSTDIR
  Call un.RemoveFromPath
  Delete "$SMPROGRAMS\VpnCloud\VpnCloud.lnk"
  Delete "$SMPROGRAMS\VpnCloud\Uninstall VpnCloud.lnk"
  RMDir "$SMPROGRAMS\VpnCloud"
  Delete "$INSTDIR\vpncloud.exe"
  Delete "$INSTDIR\vpncloud-gui.exe"
  Delete "$INSTDIR\wintun.dll"
  Delete "$INSTDIR\LICENSE.md"
  Delete "$INSTDIR\WINTUN-LICENSE.txt"
  Delete "$INSTDIR\README.txt"
  Delete "$INSTDIR\example.net.disabled"
  Delete "$INSTDIR\Uninstall.exe"
  RMDir "$INSTDIR"
  DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\VpnCloud"
  DeleteRegKey HKLM "Software\VpnCloud"
SectionEnd
