use crate::error::Error;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
#[cfg(windows)] use std::process::Command;
use std::{
    env,
    fs::{self, File},
    io::{self, Write}
};

pub struct InstallOpts {
    pub uninstall: bool,
    /// None = prompt on Windows when stdin is a TTY
    pub tray: Option<bool>,
    pub autostart: bool,
    /// None = prompt on Windows when stdin is a TTY
    pub service: Option<bool>
}

#[cfg(unix)]
const MANPAGE: &[u8] = include_bytes!("../target/vpncloud.1.gz");
#[cfg(all(unix, not(any(target_os = "macos", target_os = "freebsd"))))]
const SERVICE_FILE: &str = include_str!("../assets/vpncloud@.service");
#[cfg(all(unix, not(any(target_os = "macos", target_os = "freebsd"))))]
const TARGET_FILE: &str = include_str!("../assets/vpncloud.target");
#[cfg(all(unix, not(any(target_os = "macos", target_os = "freebsd"))))]
const WS_PROXY_SERVICE_FILE: &str = include_str!("../assets/vpncloud-wsproxy.service");
const EXAMPLE_CONFIG: &[u8] = include_bytes!("../assets/example.net.disabled");

fn prompt_yes_no(question: &str, default_yes: bool) -> bool {
    use std::io::IsTerminal;
    if !io::stdin().is_terminal() {
        return default_yes;
    }
    let hint = if default_yes { "[Y/n]" } else { "[y/N]" };
    eprint!("{} {} ", question, hint);
    let _ = io::stderr().flush();
    let mut line = String::new();
    if io::stdin().read_line(&mut line).is_err() {
        return default_yes;
    }
    match line.trim().to_ascii_lowercase().as_str() {
        "" => default_yes,
        "y" | "yes" => true,
        "n" | "no" => false,
        _ => default_yes
    }
}

pub fn install(opts: InstallOpts) -> Result<(), Error> {
    if opts.uninstall {
        return uninstall();
    }
    #[cfg(unix)]
    {
        let _ = opts;
        return install_unix();
    }
    #[cfg(windows)]
    {
        return install_windows(opts);
    }
    #[cfg(not(any(unix, windows)))]
    {
        let _ = opts;
        Err(Error::InvalidConfig("install is not supported on this platform"))
    }
}

#[cfg(unix)]
fn remove_if_exists(path: &str, msg: &'static str) -> Result<(), Error> {
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(Error::FileIo(msg, e))
    }
}

#[cfg(unix)]
fn install_unix() -> Result<(), Error> {
    let bin = crate::config::system_bin_path();
    let cfg_dir = crate::config::system_config_dir();
    let man = crate::config::system_man_path();
    if let Some(parent) = bin.parent() {
        fs::create_dir_all(parent).map_err(|e| Error::FileIo("Failed to create binary folder", e))?;
    }
    env::current_exe().and_then(|p| fs::copy(p, bin)).map_err(|e| Error::FileIo("Failed to copy binary", e))?;
    fs::set_permissions(bin, fs::Permissions::from_mode(0o755))
        .map_err(|e| Error::FileIo("Failed to set permissions for binary", e))?;
    fs::create_dir_all(cfg_dir).map_err(|e| Error::FileIo("Failed to create config folder", e))?;
    fs::set_permissions(cfg_dir, fs::Permissions::from_mode(0o700))
        .map_err(|e| Error::FileIo("Failed to set permissions for config folder", e))?;
    File::create(cfg_dir.join("example.net.disabled"))
        .and_then(|mut f| f.write_all(EXAMPLE_CONFIG))
        .map_err(|e| Error::FileIo("Failed to create example config", e))?;
    if let Some(parent) = man.parent() {
        fs::create_dir_all(parent).map_err(|e| Error::FileIo("Failed to create manpage folder", e))?;
    }
    File::create(man)
        .and_then(|mut f| f.write_all(MANPAGE))
        .map_err(|e| Error::FileIo("Failed to create manpage", e))?;
    #[cfg(target_os = "macos")]
    {
        let cfg = cfg_dir.join("vpncloud.yaml");
        if !cfg.exists() {
            fs::write(&cfg, b"# Generated by vpncloud install\nlisten: 3210\n")
                .map_err(|e| Error::FileIo("Failed to create default config", e))?;
        }
        crate::svc::install_launchd(bin.to_path_buf(), cfg)?;
        info!(
            "LaunchDaemon {} installed. Edit {} then: sudo launchctl start {}",
            crate::svc::MAC_LABEL,
            cfg_dir.join("vpncloud.yaml").display(),
            crate::svc::MAC_LABEL
        );
    }
    #[cfg(target_os = "freebsd")]
    {
        let cfg = cfg_dir.join("vpncloud.yaml");
        if !cfg.exists() {
            fs::write(&cfg, b"# Generated by vpncloud install\nlisten: 3210\n")
                .map_err(|e| Error::FileIo("Failed to create default config", e))?;
        }
        crate::svc::install_rcd(bin.to_path_buf(), cfg)?;
        info!(
            "rc.d script {} installed. Edit {} then: sudo sysrc vpncloud_enable=YES && sudo service vpncloud start",
            crate::svc::BSD_LABEL,
            cfg_dir.join("vpncloud.yaml").display()
        );
    }
    #[cfg(not(any(target_os = "macos", target_os = "freebsd")))]
    {
        crate::svc::install_systemd(SERVICE_FILE, TARGET_FILE, WS_PROXY_SERVICE_FILE)?;
    }
    info!("Install successful");
    Ok(())
}

#[cfg(windows)]
fn install_windows(opts: InstallOpts) -> Result<(), Error> {
    let base = windows_install_dir()?;
    fs::create_dir_all(&base).map_err(|e| Error::FileIo("Failed to create install folder", e))?;
    let exe_dest = base.join("vpncloud.exe");
    env::current_exe().and_then(|p| fs::copy(p, &exe_dest)).map_err(|e| Error::FileIo("Failed to copy binary", e))?;

    if let Ok(src_exe) = env::current_exe() {
        if let Some(dir) = src_exe.parent() {
            let src_dll = dir.join("wintun.dll");
            if src_dll.exists() {
                fs::copy(&src_dll, base.join("wintun.dll"))
                    .map_err(|e| Error::FileIo("Failed to copy wintun.dll", e))?;
                info!("Copied wintun.dll");
            } else {
                warn!(
                    "wintun.dll not found next to {}. TUN mode needs it: download from https://www.wintun.net/ and place it beside vpncloud.exe",
                    src_exe.display()
                );
            }
        }
    }

    File::create(base.join("example.net.disabled"))
        .and_then(|mut f| f.write_all(EXAMPLE_CONFIG))
        .map_err(|e| Error::FileIo("Failed to create example config", e))?;

    let service = opts.service.unwrap_or_else(|| {
        prompt_yes_no("Install as a Windows system service? Requires Administrator (sc start VpnCloud).", false)
    });
    let tray = if service {
        false
    } else {
        opts.tray.unwrap_or_else(|| prompt_yes_no("Install a system tray icon (Enable / Disable / Exit)?", true))
    };
    let autostart = !service
        && (opts.autostart || (tray && prompt_yes_no("Start VpnCloud with Windows (uses the tray icon)?", false)));

    let cfg_path = base.join("vpncloud.yaml");
    if !cfg_path.exists() {
        let mut body = String::from("# Generated by vpncloud install\nlisten: 3210\n");
        body.push_str(&format!("tray: {}\n", if tray { "true" } else { "false" }));
        File::create(&cfg_path)
            .and_then(|mut f| f.write_all(body.as_bytes()))
            .map_err(|e| Error::FileIo("Failed to write vpncloud.yaml", e))?;
    }

    write_start_menu_shortcut(&exe_dest, &cfg_path, tray)?;
    if autostart {
        write_run_key(&exe_dest, &cfg_path, tray)?;
        info!("Registered VpnCloud to start with Windows");
    }
    if tray {
        info!("Tray icon enabled. Run: {} --config {} --tray", exe_dest.display(), cfg_path.display());
    }
    if service {
        let svc_cfg = crate::winservice::default_config_path();
        if let Some(parent) = svc_cfg.parent() {
            let _ = fs::create_dir_all(parent);
        }
        if cfg_path.exists() {
            let _ = fs::copy(&cfg_path, &svc_cfg);
        }
        crate::winservice::install(Some(&svc_cfg), true)?;
    }
    info!("Install successful ({})", base.display());
    Ok(())
}

#[cfg(windows)]
fn windows_install_dir() -> Result<std::path::PathBuf, Error> {
    let local = env::var("LOCALAPPDATA").map_err(|_| Error::InvalidConfig("LOCALAPPDATA is not set"))?;
    Ok(std::path::PathBuf::from(local).join("VpnCloud"))
}

#[cfg(windows)]
fn write_start_menu_shortcut(exe: &std::path::Path, cfg: &std::path::Path, tray: bool) -> Result<(), Error> {
    let appdata = env::var("APPDATA").map_err(|_| Error::InvalidConfig("APPDATA is not set"))?;
    let dir = std::path::PathBuf::from(appdata).join("Microsoft/Windows/Start Menu/Programs");
    fs::create_dir_all(&dir).map_err(|e| Error::FileIo("Failed to create Start Menu folder", e))?;
    let lnk = dir.join("VpnCloud.lnk");
    let args =
        if tray { format!("--config \"{}\" --tray", cfg.display()) } else { format!("--config \"{}\"", cfg.display()) };
    let ps = format!(
        "$s=(New-Object -ComObject WScript.Shell).CreateShortcut('{}'); $s.TargetPath='{}'; $s.Arguments='{}'; $s.WorkingDirectory='{}'; $s.Save()",
        lnk.display().to_string().replace('\'', "''"),
        exe.display().to_string().replace('\'', "''"),
        args.replace('\'', "''"),
        exe.parent().unwrap_or(exe).display().to_string().replace('\'', "''")
    );
    let status = Command::new("powershell")
        .args(["-NoProfile", "-Command", &ps])
        .status()
        .map_err(|e| Error::FileIo("Failed to run PowerShell for shortcut", e))?;
    if !status.success() {
        warn!("Could not create Start Menu shortcut");
    }
    Ok(())
}

#[cfg(windows)]
fn write_run_key(exe: &std::path::Path, cfg: &std::path::Path, tray: bool) -> Result<(), Error> {
    use windows_sys::Win32::System::Registry::{
        RegCloseKey, RegCreateKeyExW, RegSetValueExW, HKEY_CURRENT_USER, KEY_WRITE, REG_SZ
    };
    let sub = wide("Software\\Microsoft\\Windows\\CurrentVersion\\Run");
    let mut hkey = std::ptr::null_mut();
    let rc = unsafe {
        RegCreateKeyExW(
            HKEY_CURRENT_USER,
            sub.as_ptr(),
            0,
            std::ptr::null(),
            0,
            KEY_WRITE,
            std::ptr::null(),
            &mut hkey,
            std::ptr::null_mut()
        )
    };
    if rc != 0 {
        return Err(Error::InvalidConfig("Failed to open HKCU Run key"));
    }
    let name = wide("VpnCloud");
    let cmd = if tray {
        format!("\"{}\" --config \"{}\" --tray", exe.display(), cfg.display())
    } else {
        format!("\"{}\" --config \"{}\"", exe.display(), cfg.display())
    };
    let value = wide(&cmd);
    let bytes = unsafe { std::slice::from_raw_parts(value.as_ptr() as *const u8, value.len() * 2) };
    let rc = unsafe { RegSetValueExW(hkey, name.as_ptr(), 0, REG_SZ, bytes.as_ptr(), bytes.len() as u32) };
    unsafe { RegCloseKey(hkey) };
    if rc != 0 {
        return Err(Error::InvalidConfig("Failed to write HKCU Run value"));
    }
    Ok(())
}

#[cfg(windows)]
fn delete_run_key() {
    use windows_sys::Win32::System::Registry::{
        RegCloseKey, RegDeleteValueW, RegOpenKeyExW, HKEY_CURRENT_USER, KEY_WRITE
    };
    let sub = wide("Software\\Microsoft\\Windows\\CurrentVersion\\Run");
    let mut hkey = std::ptr::null_mut();
    let rc = unsafe { RegOpenKeyExW(HKEY_CURRENT_USER, sub.as_ptr(), 0, KEY_WRITE, &mut hkey) };
    if rc != 0 {
        return;
    }
    let name = wide("VpnCloud");
    unsafe {
        RegDeleteValueW(hkey, name.as_ptr());
        RegCloseKey(hkey);
    }
}

#[cfg(windows)]
fn wide(s: &str) -> Vec<u16> {
    s.encode_utf16().chain(std::iter::once(0)).collect()
}

pub fn uninstall() -> Result<(), Error> {
    #[cfg(unix)]
    {
        let _ = crate::svc::uninstall_launchd();
        let _ = crate::svc::uninstall_systemd();
        let _ = crate::svc::uninstall_rcd();
        remove_if_exists("/etc/vpncloud/example.net.disabled", "Failed to remove example config")?;
        remove_if_exists("/usr/local/etc/vpncloud/example.net.disabled", "Failed to remove example config")?;
        remove_if_exists("/usr/share/man/man1/vpncloud.1.gz", "Failed to remove manpage")?;
        remove_if_exists("/usr/local/share/man/man1/vpncloud.1.gz", "Failed to remove manpage")?;
        remove_if_exists("/usr/bin/vpncloud", "Failed to remove binary")?;
        remove_if_exists("/usr/local/bin/vpncloud", "Failed to remove binary")?;
        info!("Uninstall successful");
        Ok(())
    }
    #[cfg(windows)]
    {
        delete_run_key();
        let _ = crate::winservice::uninstall();
        if let Ok(base) = windows_install_dir() {
            let _ = fs::remove_file(base.join("vpncloud.exe"));
            let _ = fs::remove_file(base.join("wintun.dll"));
            let _ = fs::remove_file(base.join("example.net.disabled"));
            let _ = fs::remove_dir(&base);
        }
        if let Ok(appdata) = env::var("APPDATA") {
            let lnk = std::path::PathBuf::from(appdata).join("Microsoft/Windows/Start Menu/Programs/VpnCloud.lnk");
            let _ = fs::remove_file(lnk);
        }
        info!("Uninstall successful");
        Ok(())
    }
    #[cfg(not(any(unix, windows)))]
    Err(Error::InvalidConfig("uninstall is not supported on this platform"))
}
