use crate::error::Error;
#[cfg(unix)]
use crate::util::run_cmd;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::{
    env,
    fs::{self, File},
    io::{self, Write},
    process::Command
};

pub struct InstallOpts {
    pub uninstall: bool,
    /// None = prompt on Windows when stdin is a TTY
    pub tray: Option<bool>,
    pub autostart: bool
}

#[cfg(unix)]
const MANPAGE: &[u8] = include_bytes!("../target/vpncloud.1.gz");
#[cfg(unix)]
const SERVICE_FILE: &[u8] = include_bytes!("../assets/vpncloud@.service");
#[cfg(unix)]
const TARGET_FILE: &[u8] = include_bytes!("../assets/vpncloud.target");
#[cfg(unix)]
const WS_PROXY_SERVICE_FILE: &[u8] = include_bytes!("../assets/vpncloud-wsproxy.service");
const EXAMPLE_CONFIG: &[u8] = include_bytes!("../assets/example.net.disabled");

fn prompt_yes_no(question: &str, default_yes: bool) -> bool {
    use std::io::IsTerminal;
    if !io::stdin().is_terminal() {
        return default_yes;
    }
    let hint = if default_yes { "[Y/n]" } else { "[y/N]" };
    eprint!("{} {} ", question, hint);
    let _ = io::stderr().flush();
    let mut line = String::new();
    if io::stdin().read_line(&mut line).is_err() {
        return default_yes;
    }
    match line.trim().to_ascii_lowercase().as_str() {
        "" => default_yes,
        "y" | "yes" => true,
        "n" | "no" => false,
        _ => default_yes
    }
}

pub fn install(opts: InstallOpts) -> Result<(), Error> {
    if opts.uninstall {
        return uninstall();
    }
    #[cfg(unix)]
    {
        let _ = opts;
        return install_unix();
    }
    #[cfg(windows)]
    {
        return install_windows(opts);
    }
    #[cfg(not(any(unix, windows)))]
    {
        let _ = opts;
        Err(Error::InvalidConfig("install is not supported on this platform"))
    }
}

#[cfg(unix)]
fn systemctl_daemon_reload() {
    let mut cmd = Command::new("systemctl");
    cmd.arg("daemon-reload");
    run_cmd(cmd);
}

#[cfg(unix)]
fn install_unix() -> Result<(), Error> {
    env::current_exe()
        .and_then(|p| fs::copy(p, "/usr/bin/vpncloud"))
        .map_err(|e| Error::FileIo("Failed to copy binary", e))?;
    fs::set_permissions("/usr/bin/vpncloud", fs::Permissions::from_mode(0o755))
        .map_err(|e| Error::FileIo("Failed to set permissions for binary", e))?;
    fs::create_dir_all("/etc/vpncloud").map_err(|e| Error::FileIo("Failed to create config folder", e))?;
    fs::set_permissions("/etc/vpncloud", fs::Permissions::from_mode(0o700))
        .map_err(|e| Error::FileIo("Failed to set permissions for config folder", e))?;
    File::create("/etc/vpncloud/example.net.disabled")
        .and_then(|mut f| f.write_all(EXAMPLE_CONFIG))
        .map_err(|e| Error::FileIo("Failed to create example config", e))?;
    File::create("/usr/share/man/man1/vpncloud.1.gz")
        .and_then(|mut f| f.write_all(MANPAGE))
        .map_err(|e| Error::FileIo("Failed to create manpage", e))?;
    File::create("/lib/systemd/system/vpncloud@.service")
        .and_then(|mut f| f.write_all(SERVICE_FILE))
        .map_err(|e| Error::FileIo("Failed to create service file", e))?;
    File::create("/lib/systemd/system/vpncloud.target")
        .and_then(|mut f| f.write_all(TARGET_FILE))
        .map_err(|e| Error::FileIo("Failed to create service target file", e))?;
    File::create("/lib/systemd/system/vpncloud-wsproxy.service")
        .and_then(|mut f| f.write_all(WS_PROXY_SERVICE_FILE))
        .map_err(|e| Error::FileIo("Failed to create wsporxy service file", e))?;
    systemctl_daemon_reload();
    info!("Install successful");
    Ok(())
}

#[cfg(windows)]
fn install_windows(opts: InstallOpts) -> Result<(), Error> {
    let base = windows_install_dir()?;
    fs::create_dir_all(&base).map_err(|e| Error::FileIo("Failed to create install folder", e))?;
    let exe_dest = base.join("vpncloud.exe");
    env::current_exe()
        .and_then(|p| fs::copy(p, &exe_dest))
        .map_err(|e| Error::FileIo("Failed to copy binary", e))?;

    File::create(base.join("example.net.disabled"))
        .and_then(|mut f| f.write_all(EXAMPLE_CONFIG))
        .map_err(|e| Error::FileIo("Failed to create example config", e))?;

    let tray = opts.tray.unwrap_or_else(|| {
        prompt_yes_no("Install a system tray icon (Enable / Disable / Exit)?", true)
    });
    let autostart = opts.autostart
        || (tray && prompt_yes_no("Start VpnCloud with Windows (uses the tray icon)?", false));

    let cfg_path = base.join("vpncloud.yaml");
    if !cfg_path.exists() {
        let mut body = String::from("# Generated by vpncloud install\nlisten: 3210\n");
        body.push_str(&format!("tray: {}\n", if tray { "true" } else { "false" }));
        File::create(&cfg_path)
            .and_then(|mut f| f.write_all(body.as_bytes()))
            .map_err(|e| Error::FileIo("Failed to write vpncloud.yaml", e))?;
    }

    write_start_menu_shortcut(&exe_dest, &cfg_path, tray)?;
    if autostart {
        write_run_key(&exe_dest, &cfg_path, tray)?;
        info!("Registered VpnCloud to start with Windows");
    }
    if tray {
        info!("Tray icon enabled. Run: {} --config {} --tray", exe_dest.display(), cfg_path.display());
    }
    info!("Install successful ({})", base.display());
    Ok(())
}

#[cfg(windows)]
fn windows_install_dir() -> Result<std::path::PathBuf, Error> {
    let local = env::var("LOCALAPPDATA").map_err(|_| Error::InvalidConfig("LOCALAPPDATA is not set"))?;
    Ok(std::path::PathBuf::from(local).join("VpnCloud"))
}

#[cfg(windows)]
fn write_start_menu_shortcut(
    exe: &std::path::Path, cfg: &std::path::Path, tray: bool
) -> Result<(), Error> {
    let appdata = env::var("APPDATA").map_err(|_| Error::InvalidConfig("APPDATA is not set"))?;
    let dir = std::path::PathBuf::from(appdata).join("Microsoft/Windows/Start Menu/Programs");
    fs::create_dir_all(&dir).map_err(|e| Error::FileIo("Failed to create Start Menu folder", e))?;
    let lnk = dir.join("VpnCloud.lnk");
    let args = if tray {
        format!("--config \"{}\" --tray", cfg.display())
    } else {
        format!("--config \"{}\"", cfg.display())
    };
    let ps = format!(
        "$s=(New-Object -ComObject WScript.Shell).CreateShortcut('{}'); $s.TargetPath='{}'; $s.Arguments='{}'; $s.WorkingDirectory='{}'; $s.Save()",
        lnk.display().to_string().replace('\'', "''"),
        exe.display().to_string().replace('\'', "''"),
        args.replace('\'', "''"),
        exe.parent().unwrap_or(exe).display().to_string().replace('\'', "''")
    );
    let status = Command::new("powershell")
        .args(["-NoProfile", "-Command", &ps])
        .status()
        .map_err(|e| Error::FileIo("Failed to run PowerShell for shortcut", e))?;
    if !status.success() {
        warn!("Could not create Start Menu shortcut");
    }
    Ok(())
}

#[cfg(windows)]
fn write_run_key(exe: &std::path::Path, cfg: &std::path::Path, tray: bool) -> Result<(), Error> {
    use windows_sys::Win32::System::Registry::{
        RegCloseKey, RegCreateKeyExW, RegSetValueExW, HKEY_CURRENT_USER, KEY_WRITE, REG_SZ
    };
    let sub = wide("Software\\Microsoft\\Windows\\CurrentVersion\\Run");
    let mut hkey = 0;
    let rc = unsafe {
        RegCreateKeyExW(HKEY_CURRENT_USER, sub.as_ptr(), 0, std::ptr::null(), 0, KEY_WRITE, std::ptr::null(), &mut hkey, std::ptr::null_mut())
    };
    if rc != 0 {
        return Err(Error::InvalidConfig("Failed to open HKCU Run key"));
    }
    let name = wide("VpnCloud");
    let cmd = if tray {
        format!("\"{}\" --config \"{}\" --tray", exe.display(), cfg.display())
    } else {
        format!("\"{}\" --config \"{}\"", exe.display(), cfg.display())
    };
    let value = wide(&cmd);
    let bytes = unsafe { std::slice::from_raw_parts(value.as_ptr() as *const u8, value.len() * 2) };
    let rc = unsafe {
        RegSetValueExW(hkey, name.as_ptr(), 0, REG_SZ, bytes.as_ptr(), bytes.len() as u32)
    };
    unsafe { RegCloseKey(hkey) };
    if rc != 0 {
        return Err(Error::InvalidConfig("Failed to write HKCU Run value"));
    }
    Ok(())
}

#[cfg(windows)]
fn delete_run_key() {
    use windows_sys::Win32::System::Registry::{RegCloseKey, RegOpenKeyExW, RegDeleteValueW, HKEY_CURRENT_USER, KEY_WRITE};
    let sub = wide("Software\\Microsoft\\Windows\\CurrentVersion\\Run");
    let mut hkey = 0;
    let rc = unsafe { RegOpenKeyExW(HKEY_CURRENT_USER, sub.as_ptr(), 0, KEY_WRITE, &mut hkey) };
    if rc != 0 {
        return;
    }
    let name = wide("VpnCloud");
    unsafe {
        RegDeleteValueW(hkey, name.as_ptr());
        RegCloseKey(hkey);
    }
}

#[cfg(windows)]
fn wide(s: &str) -> Vec<u16> {
    s.encode_utf16().chain(std::iter::once(0)).collect()
}

pub fn uninstall() -> Result<(), Error> {
    #[cfg(unix)]
    {
        fs::remove_file("/etc/vpncloud/example.net.disabled").map_err(|e| Error::FileIo("Failed to remove binary", e))?;
        fs::remove_file("/usr/share/man/man1/vpncloud.1.gz").map_err(|e| Error::FileIo("Failed to remove manpage", e))?;
        fs::remove_file("/lib/systemd/system/vpncloud@.service")
            .map_err(|e| Error::FileIo("Failed to remove service file", e))?;
        fs::remove_file("/lib/systemd/system/vpncloud.target")
            .map_err(|e| Error::FileIo("Failed to remove service target file", e))?;
        fs::remove_file("/lib/systemd/system/vpncloud-wsproxy.service")
            .map_err(|e| Error::FileIo("Failed to remove wsproxy service file", e))?;
        fs::remove_file("/usr/bin/vpncloud").map_err(|e| Error::FileIo("Failed to remove binary", e))?;
        systemctl_daemon_reload();
        info!("Uninstall successful");
        Ok(())
    }
    #[cfg(windows)]
    {
        delete_run_key();
        if let Ok(base) = windows_install_dir() {
            let _ = fs::remove_file(base.join("vpncloud.exe"));
            let _ = fs::remove_file(base.join("example.net.disabled"));
            let _ = fs::remove_dir(&base);
        }
        if let Ok(appdata) = env::var("APPDATA") {
            let lnk = std::path::PathBuf::from(appdata).join("Microsoft/Windows/Start Menu/Programs/VpnCloud.lnk");
            let _ = fs::remove_file(lnk);
        }
        info!("Uninstall successful");
        Ok(())
    }
    #[cfg(not(any(unix, windows)))]
    Err(Error::InvalidConfig("uninstall is not supported on this platform"))
}
